apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: couchdbinstances.nuvolaris.org
spec:
  group: nuvolaris.org
  names:
    kind: CouchdbInstance
    plural: couchdbinstances
    singular: couchdbinstance
    shortNames:
      - cdb
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storage:
                  type: string
                replicas:
                  type: integer
