apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: default
spec:
  containers:
  - name: kaniko
    #image: busybox
    #command:
    #- sleep
    #- inf
    image: gcr.io/kaniko-project/executor:latest
    args: 
      - --context=git://github.com/${GITHUB_USER}/openserverless-operator
      - --destination=docker-registry:5000/openserverless/operator:${TAG}
      - --insecure
      - --insecure-registry=docker-registry
    volumeMounts:
    - name: config-volume
      mountPath: /context
  restartPolicy: Never
  volumes:
  - name: config-volume
    configMap:
      name: dockerfile-configmap
