apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-history-pvc
  namespace: {{namespace}}
  labels:
    app: spark
    component: spark-history
spec:
  accessModes:
    - ReadWriteOnce
  {% if storage_class %}
  storageClassName: {{storage_class}}
  {% endif %}
  resources:
    requests:
      storage: {{history_volume_size}}Gi