apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: {{namespace}}
  labels:
    app: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark
  namespace: {{namespace}}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: {{namespace}}
subjects:
- kind: ServiceAccount
  name: spark
  namespace: {{namespace}}
roleRef:
  kind: Role
  name: spark
  apiGroup: rbac.authorization.k8s.io