#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: nuvolaris
  labels:
    app.kubernetes.io/name: apisix
    app.kubernetes.io/instance: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix
      app.kubernetes.io/instance: apisix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apisix
        app.kubernetes.io/instance: apisix
    spec:
      serviceAccountName: default
      containers:
        - name: apisix
          image: "bitnami/apisix:3.7.0"
          imagePullPolicy: IfNotPresent
          env:
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP     
            - name: tls
              containerPort: 9443
              protocol: TCP
            - name: admin
              containerPort: 9180
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9080
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "sleep 30"
          volumeMounts:
            - mountPath: /usr/local/apisix/conf/config.yaml
              name: apisix-config
              subPath: config.yaml
          resources:
            {}
      hostNetwork: false
      initContainers:
        - name: wait-etcd
          image: busybox:1.28
          command: ['sh', '-c', "until nc -z apisix-etcd.nuvolaris.svc.cluster.local 2379; do echo waiting for etcd `date`; sleep 2; done;"]
      volumes:
        - configMap:
            name: apisix
          name: apisix-config